name: Sync

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v2

      - name: Download gfwlist.txt from upstream and debug
        run: |
          # 下载文件，保存为 gfwlist.txt
          curl -L -o GFWLIST.txt https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

          # 显示当前目录文件列表
          ls -la

          # 配置 git 提交信息
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 查看 git 状态
          git status

          # 添加指定的文件
          git add gfwlist.txt

          # 再次查看 git 状态，确认文件已被添加
          git status

          # 检查是否有更改
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-sync GFWLIST.txt from upstream"
            git push origin main  # 确保这里的分支名称是 main
